{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "fd80d633",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'aiohttp'",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mModuleNotFoundError\u001b[39m                       Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[4]\u001b[39m\u001b[32m, line 1\u001b[39m\n\u001b[32m----> \u001b[39m\u001b[32m1\u001b[39m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01maiohttp\u001b[39;00m\n\u001b[32m      2\u001b[39m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01masyncio\u001b[39;00m\n\u001b[32m      3\u001b[39m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mbs4\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m BeautifulSoup\n",
      "\u001b[31mModuleNotFoundError\u001b[39m: No module named 'aiohttp'"
     ]
    }
   ],
   "source": [
    "import aiohttp\n",
    "import asyncio\n",
    "from bs4 import BeautifulSoup\n",
    "import time\n",
    "from typing import List, Dict\n",
    "\n",
    "class WebScraper:\n",
    "    \"\"\"\n",
    "    Web Scraper Assíncrono usando aiohttp e BeautifulSoup para extração de dados.\n",
    "    \"\"\"\n",
    "    def __init__(self):\n",
    "        self.session = None\n",
    "    \n",
    "    async def fetch_url(self, url: str) -> str:\n",
    "        \"\"\"\n",
    "        Busca o conteúdo HTML de uma URL de forma assíncrona.\n",
    "        \"\"\"\n",
    "        try:\n",
    "            # Reusa a sessão do ClientSession\n",
    "            async with self.session.get(url) as response:\n",
    "                response.raise_for_status() # Lança erro para códigos de status HTTP 4xx/5xx\n",
    "                print(f\"  [SUCESSO] Fetched: {url}\")\n",
    "                return await response.text()\n",
    "        except aiohttp.ClientError as e:\n",
    "            print(f\"  [ERRO] Falha ao buscar {url}: {e}\")\n",
    "            return \"\"\n",
    "\n",
    "    async def scrape_multiplas_paginas(self, urls: List[str]) -> List[str]:\n",
    "        \"\"\"\n",
    "        Coordena a busca assíncrona de múltiplas URLs.\n",
    "        \"\"\"\n",
    "        start_time = time.time()\n",
    "        \n",
    "        # Cria uma sessão aiohttp que será usada por todas as tarefas\n",
    "        async with aiohttp.ClientSession() as session:\n",
    "            self.session = session\n",
    "            \n",
    "            # Cria tarefas (Tasks) para cada URL\n",
    "            tasks = [self.fetch_url(url) for url in urls]\n",
    "            \n",
    "            # Executa todas as tarefas simultaneamente\n",
    "            results = await asyncio.gather(*tasks)\n",
    "            \n",
    "        end_time = time.time()\n",
    "        print(f\"\\n[INFO] Tempo total de scraping: {end_time - start_time:.2f} segundos\")\n",
    "        return [res for res in results if res] # Retorna apenas HTML válido\n",
    "\n",
    "    def extrair_dados(self, html: str) -> List[Dict]:\n",
    "        \"\"\"\n",
    "        Extrai títulos de notícias (ou elementos genéricos <h2>) de uma string HTML.\n",
    "        \"\"\"\n",
    "        if not html:\n",
    "            return []\n",
    "\n",
    "        soup = BeautifulSoup(html, 'html.parser')\n",
    "        \n",
    "        # Exemplo de extração: busca todos os títulos <h2> e seus links se existirem\n",
    "        dados_extraidos = []\n",
    "        for h2 in soup.find_all('h2'):\n",
    "            titulo = h2.get_text(strip=True)\n",
    "            link = h2.find_parent('a')['href'] if h2.find_parent('a') else 'N/A'\n",
    "            dados_extraidos.append({\n",
    "                'titulo': titulo,\n",
    "                'link': link\n",
    "            })\n",
    "        \n",
    "        return dados_extraidos\n",
    "\n",
    "async def main_scraper():\n",
    "    # Usando URLs de exemplo (substitua por URLs reais de interesse)\n",
    "    urls_de_exemplo = [\n",
    "        \"http://quotes.toscrape.com/\",\n",
    "        \"http://quotes.toscrape.com/page/2/\",\n",
    "        # Adicione mais URLs para ver a performance assíncrona\n",
    "    ]\n",
    "    \n",
    "    print(\"Iniciando scraping assíncrono...\")\n",
    "    scraper = WebScraper()\n",
    "    htmls = await scraper.scrape_multiplas_paginas(urls_de_exemplo)\n",
    "    \n",
    "    dados_totais = []\n",
    "    for i, html in enumerate(htmls):\n",
    "        print(f\"\\n[PARSING] Extraindo dados da página {i+1}...\")\n",
    "        dados = scraper.extrair_dados(html)\n",
    "        dados_totais.extend(dados)\n",
    "        \n",
    "    print(f\"\\n[RESULTADO FINAL] Total de {len(dados_totais)} itens extraídos.\")\n",
    "    # print(dados_totais[:5]) # Imprime os primeiros 5 itens\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    # Executa a função assíncrona\n",
    "    asyncio.run(main_scraper())"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
